// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dajeojcchvfpakuparda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhamVvamNjaHZmcGFrdXBhcmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Mjg1NjUsImV4cCI6MjA3MDQwNDU2NX0.3KegvD97Tshavupupx__xf0Y7YfJTi006XIqn90emag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});